version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  jaguar:
    build: .
    restart: always
    depends_on:
       - db
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      DATABASE_URL: "host=db port=5432 user=root password=root sslmode=disable"